/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//Address of the clock control register (AHB1ENR)
	uint32_t *pClk = (uint32_t*)0x40023830;
	//Address of the GPIOD mode register (used to control the mode)
	uint32_t *pClkModeReg = (uint32_t*)0x40020C00;
	//Address of the GPIOD output data register (use to write)
	uint32_t *pClkOutDataReg = (uint32_t*)0x40020C14;

	//1. Enable the clock for  GPIO peripheral for AHB1ENR
	*pClk = *pClk | (1 << 3); //set the 3'th bit

	//2. Configure the mode of the IO pin as output
	*pClkModeReg &= ~(3 << 24); //clear the 24'th and 25'th bit position
	*pClkModeReg |= (1 << 24); //make 24'th bit position to 1

	while(1)
	{
		//3. Set the 12'th bit of the output data register to make I/O pin12 as HIGH
		*pClkOutDataReg |= (1<<12);
		//introducing of a small observable delay with a loop
		for(uint32_t i = 0; i < 300000; i++);
		//Turn off the LED (clear the 12'th bit of the output data register)
		*pClkOutDataReg &= ~(1<<12);
		//introducing of a small observable delay with a loop
		for(uint32_t i = 0; i < 300000; i++);
	}
}
